/* Colour.c generated by valac 0.16.1, the Vala compiler
 * generated from Colour.vala, do not modify */

/* Colour.vala
 *
 * Copyright (C) 2013  Ross Taylor
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Ross Taylor <the.mighty.ug@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define LED_BORG_TYPE_COLOUR (led_borg_colour_get_type ())
typedef struct _LedBorgColour LedBorgColour;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

struct _LedBorgColour {
	gint red;
	gint green;
	gint blue;
};



GType led_borg_colour_get_type (void) G_GNUC_CONST;
LedBorgColour* led_borg_colour_dup (const LedBorgColour* self);
void led_borg_colour_free (LedBorgColour* self);
void led_borg_colour_init_with_rgb (LedBorgColour *self, const gchar* rgb);
gchar* led_borg_colour_to_string (LedBorgColour *self);
gchar* led_borg_colour_get_ledborg_value (LedBorgColour *self);
gchar* led_borg_colour_get_html_value (LedBorgColour *self);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_;
		gint _tmp8_;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_;
		glong _tmp14_;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_;
		glong _tmp17_;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


void led_borg_colour_init_with_rgb (LedBorgColour *self, const gchar* rgb) {
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	gint _tmp3_ = 0;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	gint _tmp7_ = 0;
	const gchar* _tmp8_;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	gint _tmp11_ = 0;
	g_return_if_fail (rgb != NULL);
	memset (self, 0, sizeof (LedBorgColour));
	_tmp0_ = rgb;
	_tmp1_ = string_substring (_tmp0_, (glong) 0, (glong) 1);
	_tmp2_ = _tmp1_;
	_tmp3_ = atoi (_tmp2_);
	(*self).red = _tmp3_;
	_g_free0 (_tmp2_);
	_tmp4_ = rgb;
	_tmp5_ = string_substring (_tmp4_, (glong) 1, (glong) 1);
	_tmp6_ = _tmp5_;
	_tmp7_ = atoi (_tmp6_);
	(*self).green = _tmp7_;
	_g_free0 (_tmp6_);
	_tmp8_ = rgb;
	_tmp9_ = string_substring (_tmp8_, (glong) 2, (glong) 1);
	_tmp10_ = _tmp9_;
	_tmp11_ = atoi (_tmp10_);
	(*self).blue = _tmp11_;
	_g_free0 (_tmp10_);
}


gchar* led_borg_colour_to_string (LedBorgColour *self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	_tmp0_ = led_borg_colour_get_ledborg_value (&(*self));
	result = _tmp0_;
	return result;
}


gchar* led_borg_colour_get_ledborg_value (LedBorgColour *self) {
	gchar* result = NULL;
	GString* _tmp0_;
	GString* c;
	gint _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gint _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	gint _tmp7_;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	_tmp0_ = g_string_new ("");
	c = _tmp0_;
	_tmp1_ = (*self).red;
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
	_tmp3_ = _tmp2_;
	g_string_append (c, _tmp3_);
	_g_free0 (_tmp3_);
	_tmp4_ = (*self).green;
	_tmp5_ = g_strdup_printf ("%i", _tmp4_);
	_tmp6_ = _tmp5_;
	g_string_append (c, _tmp6_);
	_g_free0 (_tmp6_);
	_tmp7_ = (*self).blue;
	_tmp8_ = g_strdup_printf ("%i", _tmp7_);
	_tmp9_ = _tmp8_;
	g_string_append (c, _tmp9_);
	_g_free0 (_tmp9_);
	_tmp10_ = c->str;
	_tmp11_ = g_strdup (_tmp10_);
	result = _tmp11_;
	_g_string_free0 (c);
	return result;
}


gchar* led_borg_colour_get_html_value (LedBorgColour *self) {
	gchar* result = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_ = NULL;
	gchar** lookup;
	gint lookup_length1;
	gint _lookup_size_;
	GString* _tmp4_;
	GString* html;
	gint _tmp5_;
	const gchar* _tmp6_;
	gint _tmp7_;
	const gchar* _tmp8_;
	gint _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	_tmp0_ = g_strdup ("00");
	_tmp1_ = g_strdup ("bb");
	_tmp2_ = g_strdup ("ff");
	_tmp3_ = g_new0 (gchar*, 3 + 1);
	_tmp3_[0] = _tmp0_;
	_tmp3_[1] = _tmp1_;
	_tmp3_[2] = _tmp2_;
	lookup = _tmp3_;
	lookup_length1 = 3;
	_lookup_size_ = lookup_length1;
	_tmp4_ = g_string_new ("#");
	html = _tmp4_;
	_tmp5_ = (*self).red;
	_tmp6_ = lookup[_tmp5_];
	g_string_append (html, _tmp6_);
	_tmp7_ = (*self).green;
	_tmp8_ = lookup[_tmp7_];
	g_string_append (html, _tmp8_);
	_tmp9_ = (*self).blue;
	_tmp10_ = lookup[_tmp9_];
	g_string_append (html, _tmp10_);
	_tmp11_ = html->str;
	_tmp12_ = g_strdup (_tmp11_);
	result = _tmp12_;
	_g_string_free0 (html);
	lookup = (_vala_array_free (lookup, lookup_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


LedBorgColour* led_borg_colour_dup (const LedBorgColour* self) {
	LedBorgColour* dup;
	dup = g_new0 (LedBorgColour, 1);
	memcpy (dup, self, sizeof (LedBorgColour));
	return dup;
}


void led_borg_colour_free (LedBorgColour* self) {
	g_free (self);
}


GType led_borg_colour_get_type (void) {
	static volatile gsize led_borg_colour_type_id__volatile = 0;
	if (g_once_init_enter (&led_borg_colour_type_id__volatile)) {
		GType led_borg_colour_type_id;
		led_borg_colour_type_id = g_boxed_type_register_static ("LedBorgColour", (GBoxedCopyFunc) led_borg_colour_dup, (GBoxedFreeFunc) led_borg_colour_free);
		g_once_init_leave (&led_borg_colour_type_id__volatile, led_borg_colour_type_id);
	}
	return led_borg_colour_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



