/* main.c generated by valac 0.16.1, the Vala compiler
 * generated from main.vala, do not modify */

/* applet/main.vala
 *
 * Copyright (C) 2013  Ross Taylor
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Ross Taylor <the.mighty.ug@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gtk/gtk.h>


#define LED_BORG_TYPE_MAIN (led_borg_main_get_type ())
#define LED_BORG_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LED_BORG_TYPE_MAIN, LedBorgMain))
#define LED_BORG_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LED_BORG_TYPE_MAIN, LedBorgMainClass))
#define LED_BORG_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LED_BORG_TYPE_MAIN))
#define LED_BORG_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LED_BORG_TYPE_MAIN))
#define LED_BORG_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LED_BORG_TYPE_MAIN, LedBorgMainClass))

typedef struct _LedBorgMain LedBorgMain;
typedef struct _LedBorgMainClass LedBorgMainClass;
typedef struct _LedBorgMainPrivate LedBorgMainPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define LED_BORG_TYPE_LED_BORG_CONTROL_APPLET (led_borg_led_borg_control_applet_get_type ())
#define LED_BORG_LED_BORG_CONTROL_APPLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LED_BORG_TYPE_LED_BORG_CONTROL_APPLET, LedBorgLedBorgControlApplet))
#define LED_BORG_LED_BORG_CONTROL_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LED_BORG_TYPE_LED_BORG_CONTROL_APPLET, LedBorgLedBorgControlAppletClass))
#define LED_BORG_IS_LED_BORG_CONTROL_APPLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LED_BORG_TYPE_LED_BORG_CONTROL_APPLET))
#define LED_BORG_IS_LED_BORG_CONTROL_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LED_BORG_TYPE_LED_BORG_CONTROL_APPLET))
#define LED_BORG_LED_BORG_CONTROL_APPLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LED_BORG_TYPE_LED_BORG_CONTROL_APPLET, LedBorgLedBorgControlAppletClass))

typedef struct _LedBorgLedBorgControlApplet LedBorgLedBorgControlApplet;
typedef struct _LedBorgLedBorgControlAppletClass LedBorgLedBorgControlAppletClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LedBorgMain {
	GObject parent_instance;
	LedBorgMainPrivate * priv;
};

struct _LedBorgMainClass {
	GObjectClass parent_class;
};


static gpointer led_borg_main_parent_class = NULL;
static gboolean led_borg_main__show_version;
static gboolean led_borg_main__show_version = FALSE;
static gchar* led_borg_main__host;
static gchar* led_borg_main__host = NULL;
static guint led_borg_main__port;
static guint led_borg_main__port = (guint) 9999;

GType led_borg_main_get_type (void) G_GNUC_CONST;
enum  {
	LED_BORG_MAIN_DUMMY_PROPERTY
};
static gint led_borg_main_main (gchar** args, int args_length1);
LedBorgLedBorgControlApplet* led_borg_led_borg_control_applet_new (const gchar* host, guint port);
LedBorgLedBorgControlApplet* led_borg_led_borg_control_applet_construct (GType object_type, const gchar* host, guint port);
GType led_borg_led_borg_control_applet_get_type (void) G_GNUC_CONST;
LedBorgMain* led_borg_main_new (void);
LedBorgMain* led_borg_main_construct (GType object_type);
static void led_borg_main_finalize (GObject* obj);

static const GOptionEntry LED_BORG_MAIN_options[4] = {{"ledborg-host", 'h', 0, G_OPTION_ARG_STRING, &led_borg_main__host, "Specify the server hostname or IP address", "HOST OR IP ADDRESS"}, {"ledborg-port", 'p', 0, G_OPTION_ARG_INT, &led_borg_main__port, "Specify the server port", "PORT"}, {"version", 'V', 0, G_OPTION_ARG_NONE, &led_borg_main__show_version, "Show version information", NULL}, {NULL}};

static gint led_borg_main_main (gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp13_;
	const gchar* _tmp15_;
	guint _tmp16_;
	LedBorgLedBorgControlApplet* _tmp17_;
	LedBorgLedBorgControlApplet* app;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* _tmp0_;
		GOptionContext* opt;
		GOptionContext* _tmp1_;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
		GOptionContext* _tmp4_;
		GOptionContext* _tmp5_;
		GOptionContext* _tmp6_;
		_tmp0_ = g_option_context_new ("");
		opt = _tmp0_;
		_tmp1_ = opt;
		_tmp2_ = g_strdup_printf ("LedBorg Control Applet %s is a systray app that allows you to control " \
"an LedBorg server running on a Raspberry Pi", VERSION);
		_tmp3_ = _tmp2_;
		g_option_context_set_summary (_tmp1_, _tmp3_);
		_g_free0 (_tmp3_);
		_tmp4_ = opt;
		g_option_context_set_help_enabled (_tmp4_, TRUE);
		_tmp5_ = opt;
		g_option_context_add_main_entries (_tmp5_, LED_BORG_MAIN_options, NULL);
		_tmp6_ = opt;
		g_option_context_parse (_tmp6_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch0_g_option_error;
			}
			_g_option_context_free0 (opt);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (opt);
	}
	goto __finally0;
	__catch0_g_option_error:
	{
		GError* e = NULL;
		FILE* _tmp7_;
		GError* _tmp8_;
		const gchar* _tmp9_;
		FILE* _tmp10_;
		gchar** _tmp11_;
		gint _tmp11__length1;
		const gchar* _tmp12_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = stderr;
		_tmp8_ = e;
		_tmp9_ = _tmp8_->message;
		fprintf (_tmp7_, "Error: %s\n", _tmp9_);
		_tmp10_ = stderr;
		_tmp11_ = args;
		_tmp11__length1 = args_length1;
		_tmp12_ = _tmp11_[0];
		fprintf (_tmp10_, "Run '%s --help' to see a full list of available options\n", _tmp12_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp13_ = led_borg_main__show_version;
	if (_tmp13_) {
		FILE* _tmp14_;
		_tmp14_ = stdout;
		fprintf (_tmp14_, "LedBorg Control Applet version %s\n", VERSION);
		result = 0;
		return result;
	}
	gtk_init (&args_length1, &args);
	_tmp15_ = led_borg_main__host;
	_tmp16_ = led_borg_main__port;
	_tmp17_ = led_borg_led_borg_control_applet_new (_tmp15_, (guint) _tmp16_);
	app = _tmp17_;
	gtk_main ();
	result = 0;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return led_borg_main_main (argv, argc);
}


LedBorgMain* led_borg_main_construct (GType object_type) {
	LedBorgMain * self = NULL;
	self = (LedBorgMain*) g_object_new (object_type, NULL);
	return self;
}


LedBorgMain* led_borg_main_new (void) {
	return led_borg_main_construct (LED_BORG_TYPE_MAIN);
}


static void led_borg_main_class_init (LedBorgMainClass * klass) {
	gchar* _tmp0_;
	led_borg_main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = led_borg_main_finalize;
	_tmp0_ = g_strdup ("127.0.0.1");
	led_borg_main__host = _tmp0_;
}


static void led_borg_main_instance_init (LedBorgMain * self) {
}


static void led_borg_main_finalize (GObject* obj) {
	LedBorgMain * self;
	self = LED_BORG_MAIN (obj);
	G_OBJECT_CLASS (led_borg_main_parent_class)->finalize (obj);
}


GType led_borg_main_get_type (void) {
	static volatile gsize led_borg_main_type_id__volatile = 0;
	if (g_once_init_enter (&led_borg_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LedBorgMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) led_borg_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LedBorgMain), 0, (GInstanceInitFunc) led_borg_main_instance_init, NULL };
		GType led_borg_main_type_id;
		led_borg_main_type_id = g_type_register_static (G_TYPE_OBJECT, "LedBorgMain", &g_define_type_info, 0);
		g_once_init_leave (&led_borg_main_type_id__volatile, led_borg_main_type_id);
	}
	return led_borg_main_type_id__volatile;
}



