/* RequestError.c generated by valac 0.16.1, the Vala compiler
 * generated from RequestError.vala, do not modify */

/* RequestError.vala
 *
 * Copyright (C) 2013  Ross Taylor
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Ross Taylor <the.mighty.ug@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>


typedef enum  {
	REQUEST_ERROR_COLOUR_REQUEST_INVALID,
	REQUEST_ERROR_GENERAL
} RequestError;
#define REQUEST_ERROR request_error_quark ()


GQuark request_error_quark (void);


GQuark request_error_quark (void) {
	return g_quark_from_static_string ("request_error-quark");
}



