/* Device.c generated by valac 0.16.1, the Vala compiler
 * generated from Device.vala, do not modify */

/*
 * Device.vala
 * This file is part of LedBorg-Server
 *
 * Copyright (C) 2013 - Ross Taylor
 *
 * LedBorg-Server is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * LedBorg-Server is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LedBorg-Server. If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <stdio.h>


#define LED_BORG_TYPE_DEVICE (led_borg_device_get_type ())
#define LED_BORG_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LED_BORG_TYPE_DEVICE, LedBorgDevice))
#define LED_BORG_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LED_BORG_TYPE_DEVICE, LedBorgDeviceClass))
#define LED_BORG_IS_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LED_BORG_TYPE_DEVICE))
#define LED_BORG_IS_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LED_BORG_TYPE_DEVICE))
#define LED_BORG_DEVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LED_BORG_TYPE_DEVICE, LedBorgDeviceClass))

typedef struct _LedBorgDevice LedBorgDevice;
typedef struct _LedBorgDeviceClass LedBorgDeviceClass;
typedef struct _LedBorgDevicePrivate LedBorgDevicePrivate;

#define LED_BORG_TYPE_COLOUR (led_borg_colour_get_type ())
typedef struct _LedBorgColour LedBorgColour;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))

struct _LedBorgDevice {
	GObject parent_instance;
	LedBorgDevicePrivate * priv;
};

struct _LedBorgDeviceClass {
	GObjectClass parent_class;
};

struct _LedBorgColour {
	gint red;
	gint green;
	gint blue;
};

typedef enum  {
	IO_ERROR_FILE_NOT_FOUND,
	IO_ERROR_COMMUNICATION_BREAKDOWN,
	IO_ERROR_GENERAL
} IOError;
#define IO_ERROR io_error_quark ()

static gpointer led_borg_device_parent_class = NULL;

GType led_borg_device_get_type (void) G_GNUC_CONST;
enum  {
	LED_BORG_DEVICE_DUMMY_PROPERTY
};
#define LED_BORG_DEVICE_DEVICE "/dev/ledborg"
GType led_borg_colour_get_type (void) G_GNUC_CONST;
LedBorgColour* led_borg_colour_dup (const LedBorgColour* self);
void led_borg_colour_free (LedBorgColour* self);
GQuark io_error_quark (void);
void led_borg_device_get_colour (LedBorgColour* result, GError** error);
void led_borg_colour_init_with_rgb (LedBorgColour *self, const gchar* rgb);
void led_borg_device_set_colour (LedBorgColour* colour, GError** error);
gchar* led_borg_colour_get_ledborg_value (LedBorgColour *self);
LedBorgDevice* led_borg_device_new (void);
LedBorgDevice* led_borg_device_construct (GType object_type);


void led_borg_device_get_colour (LedBorgColour* result, GError** error) {
	gchar* _tmp0_;
	gchar* colour_text;
	GFile* _tmp1_ = NULL;
	GFile* file;
	GFile* _tmp2_;
	gboolean _tmp3_ = FALSE;
	const gchar* _tmp13_;
	LedBorgColour _tmp14_ = {0};
	GError * _inner_error_ = NULL;
	_tmp0_ = g_strdup ("");
	colour_text = _tmp0_;
	_tmp1_ = g_file_new_for_path (LED_BORG_DEVICE_DEVICE);
	file = _tmp1_;
	_tmp2_ = file;
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
	if (_tmp3_) {
		{
			gsize length = 0UL;
			gchar* _tmp4_ = NULL;
			gsize _tmp5_ = 0UL;
			g_file_get_contents (LED_BORG_DEVICE_DEVICE, &_tmp4_, &_tmp5_, &_inner_error_);
			_g_free0 (colour_text);
			colour_text = _tmp4_;
			length = _tmp5_;
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_FILE_ERROR) {
					goto __catch4_g_file_error;
				}
				_g_object_unref0 (file);
				_g_free0 (colour_text);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
		goto __finally4;
		__catch4_g_file_error:
		{
			GError* e = NULL;
			GError* _tmp6_;
			const gchar* _tmp7_;
			GError* _tmp8_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp6_ = e;
			_tmp7_ = _tmp6_->message;
			_tmp8_ = g_error_new_literal (IO_ERROR, IO_ERROR_GENERAL, _tmp7_);
			_inner_error_ = _tmp8_;
			_g_error_free0 (e);
			goto __finally4;
		}
		__finally4:
		if (_inner_error_ != NULL) {
			if ((_inner_error_->domain == IO_ERROR) || (_inner_error_->domain == IO_ERROR)) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (file);
				_g_free0 (colour_text);
				return;
			} else {
				_g_object_unref0 (file);
				_g_free0 (colour_text);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	} else {
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_;
		GError* _tmp11_;
		GError* _tmp12_;
		_tmp9_ = g_strdup_printf ("Device or driver not present. %s not found.", LED_BORG_DEVICE_DEVICE);
		_tmp10_ = _tmp9_;
		_tmp11_ = g_error_new_literal (IO_ERROR, IO_ERROR_FILE_NOT_FOUND, _tmp10_);
		_tmp12_ = _tmp11_;
		_g_free0 (_tmp10_);
		_inner_error_ = _tmp12_;
		if ((_inner_error_->domain == IO_ERROR) || (_inner_error_->domain == IO_ERROR)) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (file);
			_g_free0 (colour_text);
			return;
		} else {
			_g_object_unref0 (file);
			_g_free0 (colour_text);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp13_ = colour_text;
	led_borg_colour_init_with_rgb (&_tmp14_, _tmp13_);
	*result = _tmp14_;
	_g_object_unref0 (file);
	_g_free0 (colour_text);
	return;
}


void led_borg_device_set_colour (LedBorgColour* colour, GError** error) {
	GFile* _tmp0_ = NULL;
	GFile* file;
	GFile* _tmp1_;
	gboolean _tmp2_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (colour != NULL);
	_tmp0_ = g_file_new_for_path (LED_BORG_DEVICE_DEVICE);
	file = _tmp0_;
	_tmp1_ = file;
	_tmp2_ = g_file_query_exists (_tmp1_, NULL);
	if (_tmp2_) {
		FILE* _tmp3_ = NULL;
		FILE* f;
		FILE* _tmp4_;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		_tmp3_ = fopen (LED_BORG_DEVICE_DEVICE, "w");
		f = _tmp3_;
		_tmp4_ = f;
		_tmp5_ = led_borg_colour_get_ledborg_value (colour);
		_tmp6_ = _tmp5_;
		fputs (_tmp6_, _tmp4_);
		_g_free0 (_tmp6_);
		_fclose0 (f);
	} else {
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		GError* _tmp9_;
		GError* _tmp10_;
		_tmp7_ = g_strdup_printf ("Device or driver not present. %s not found.", LED_BORG_DEVICE_DEVICE);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_error_new_literal (IO_ERROR, IO_ERROR_FILE_NOT_FOUND, _tmp8_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		_inner_error_ = _tmp10_;
		if (_inner_error_->domain == IO_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (file);
			return;
		} else {
			_g_object_unref0 (file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (file);
}


LedBorgDevice* led_borg_device_construct (GType object_type) {
	LedBorgDevice * self = NULL;
	self = (LedBorgDevice*) g_object_new (object_type, NULL);
	return self;
}


LedBorgDevice* led_borg_device_new (void) {
	return led_borg_device_construct (LED_BORG_TYPE_DEVICE);
}


static void led_borg_device_class_init (LedBorgDeviceClass * klass) {
	led_borg_device_parent_class = g_type_class_peek_parent (klass);
}


static void led_borg_device_instance_init (LedBorgDevice * self) {
}


GType led_borg_device_get_type (void) {
	static volatile gsize led_borg_device_type_id__volatile = 0;
	if (g_once_init_enter (&led_borg_device_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LedBorgDeviceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) led_borg_device_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LedBorgDevice), 0, (GInstanceInitFunc) led_borg_device_instance_init, NULL };
		GType led_borg_device_type_id;
		led_borg_device_type_id = g_type_register_static (G_TYPE_OBJECT, "LedBorgDevice", &g_define_type_info, 0);
		g_once_init_leave (&led_borg_device_type_id__volatile, led_borg_device_type_id);
	}
	return led_borg_device_type_id__volatile;
}



