/* main.c generated by valac 0.16.1, the Vala compiler
 * generated from main.vala, do not modify */

/* main.vala
 *
 * Copyright (C) 2013  Ross Taylor
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author:
 * 	Ross Taylor <the.mighty.ug@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <libsoup/soup.h>


#define LED_BORG_TYPE_MAIN (led_borg_main_get_type ())
#define LED_BORG_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LED_BORG_TYPE_MAIN, LedBorgMain))
#define LED_BORG_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LED_BORG_TYPE_MAIN, LedBorgMainClass))
#define LED_BORG_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LED_BORG_TYPE_MAIN))
#define LED_BORG_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LED_BORG_TYPE_MAIN))
#define LED_BORG_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LED_BORG_TYPE_MAIN, LedBorgMainClass))

typedef struct _LedBorgMain LedBorgMain;
typedef struct _LedBorgMainClass LedBorgMainClass;
typedef struct _LedBorgMainPrivate LedBorgMainPrivate;
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define LED_BORG_TYPE_LED_BORG_SERVER (led_borg_led_borg_server_get_type ())
#define LED_BORG_LED_BORG_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LED_BORG_TYPE_LED_BORG_SERVER, LedBorgLedBorgServer))
#define LED_BORG_LED_BORG_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LED_BORG_TYPE_LED_BORG_SERVER, LedBorgLedBorgServerClass))
#define LED_BORG_IS_LED_BORG_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LED_BORG_TYPE_LED_BORG_SERVER))
#define LED_BORG_IS_LED_BORG_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LED_BORG_TYPE_LED_BORG_SERVER))
#define LED_BORG_LED_BORG_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LED_BORG_TYPE_LED_BORG_SERVER, LedBorgLedBorgServerClass))

typedef struct _LedBorgLedBorgServer LedBorgLedBorgServer;
typedef struct _LedBorgLedBorgServerClass LedBorgLedBorgServerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LedBorgMain {
	GObject parent_instance;
	LedBorgMainPrivate * priv;
};

struct _LedBorgMainClass {
	GObjectClass parent_class;
};


static gpointer led_borg_main_parent_class = NULL;
static gint led_borg_main_listen_port;
static gint led_borg_main_listen_port = 9999;

GType led_borg_main_get_type (void) G_GNUC_CONST;
enum  {
	LED_BORG_MAIN_DUMMY_PROPERTY
};
static gint led_borg_main_main (gchar** args, int args_length1);
LedBorgLedBorgServer* led_borg_led_borg_server_new_with_listen_port (gint listen_port);
LedBorgLedBorgServer* led_borg_led_borg_server_construct_with_listen_port (GType object_type, gint listen_port);
GType led_borg_led_borg_server_get_type (void) G_GNUC_CONST;
LedBorgMain* led_borg_main_new (void);
LedBorgMain* led_borg_main_construct (GType object_type);
static void led_borg_main_finalize (GObject* obj);

static const GOptionEntry LED_BORG_MAIN_options[2] = {{"port", 'p', 0, G_OPTION_ARG_INT, &led_borg_main_listen_port, "Specify which port to listen on", NULL}, {NULL}};

static gint led_borg_main_main (gchar** args, int args_length1) {
	gint result = 0;
	gint _tmp10_;
	LedBorgLedBorgServer* _tmp11_;
	LedBorgLedBorgServer* server;
	LedBorgLedBorgServer* _tmp12_;
	GError * _inner_error_ = NULL;
	{
		GOptionContext* _tmp0_;
		GOptionContext* opt;
		GOptionContext* _tmp1_;
		GOptionContext* _tmp2_;
		GOptionContext* _tmp3_;
		_tmp0_ = g_option_context_new ("");
		opt = _tmp0_;
		_tmp1_ = opt;
		g_option_context_set_help_enabled (_tmp1_, TRUE);
		_tmp2_ = opt;
		g_option_context_add_main_entries (_tmp2_, LED_BORG_MAIN_options, NULL);
		_tmp3_ = opt;
		g_option_context_parse (_tmp3_, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			goto __catch0_g_error;
		}
		_g_option_context_free0 (opt);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		FILE* _tmp7_;
		gchar** _tmp8_;
		gint _tmp8__length1;
		const gchar* _tmp9_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stderr;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "Error: %s\n", _tmp6_);
		_tmp7_ = stderr;
		_tmp8_ = args;
		_tmp8__length1 = args_length1;
		_tmp9_ = _tmp8_[0];
		fprintf (_tmp7_, "Run '%s --help' to see a full list of available options\n", _tmp9_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp10_ = led_borg_main_listen_port;
	_tmp11_ = led_borg_led_borg_server_new_with_listen_port (_tmp10_);
	server = _tmp11_;
	_tmp12_ = server;
	soup_server_run ((SoupServer*) _tmp12_);
	result = 0;
	_g_object_unref0 (server);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return led_borg_main_main (argv, argc);
}


LedBorgMain* led_borg_main_construct (GType object_type) {
	LedBorgMain * self = NULL;
	self = (LedBorgMain*) g_object_new (object_type, NULL);
	return self;
}


LedBorgMain* led_borg_main_new (void) {
	return led_borg_main_construct (LED_BORG_TYPE_MAIN);
}


static void led_borg_main_class_init (LedBorgMainClass * klass) {
	led_borg_main_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = led_borg_main_finalize;
}


static void led_borg_main_instance_init (LedBorgMain * self) {
}


static void led_borg_main_finalize (GObject* obj) {
	LedBorgMain * self;
	self = LED_BORG_MAIN (obj);
	G_OBJECT_CLASS (led_borg_main_parent_class)->finalize (obj);
}


GType led_borg_main_get_type (void) {
	static volatile gsize led_borg_main_type_id__volatile = 0;
	if (g_once_init_enter (&led_borg_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LedBorgMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) led_borg_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LedBorgMain), 0, (GInstanceInitFunc) led_borg_main_instance_init, NULL };
		GType led_borg_main_type_id;
		led_borg_main_type_id = g_type_register_static (G_TYPE_OBJECT, "LedBorgMain", &g_define_type_info, 0);
		g_once_init_leave (&led_borg_main_type_id__volatile, led_borg_main_type_id);
	}
	return led_borg_main_type_id__volatile;
}



